---
title: "snf-cost-report-2022"
format: html
editor: visual
---

## Read CSV

```{r}
library(tidyverse)
library(tidygeocoder)

data <- read_csv("snf-cost-report-2022.csv")
```

```{r}
data |>
  ggplot(aes(x = `Rural versus Urban`)) +
  geom_bar() +
  theme_minimal()
```

```{r}
data_long <- data %>%
  pivot_longer(
    cols = c(`Total Days Title V`, `Total Days Title XVIII`, `Total Days Title XIX`),   # Replace with your real column names
    names_to = "variable",
    values_to = "value"
  )
```

```{r}
ggplot(data_long, aes(x = variable, y = value, fill = variable)) +
  geom_violin(alpha = 0.7) +
  geom_boxplot(width = 0.1, outlier.shape = NA) + 
  theme_minimal() +
  theme(legend.position = "none")
```

```{r}
state_counts <- data %>%
  count(`State Code`, name = "count")

```

```{r}
library(ggplot2)
library(maps)

states_map <- map_data("state")

```

```{r}
state_abbr_to_name <- tibble(
  State = state.abb,
  region = tolower(state.name)
)

# Join counts to full state names
state_counts <- state_counts %>%
  left_join(state_abbr_to_name, by = "State Code")

```
